version: "3.2"

services:

  redischat:
    container_name: twitch-clone-redis-chat
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test:
        - "CMD"
        - "redis-cli"
        - "ping"
      interval: 30s
      timeout: 10s
      retries: 3
